<?php
/*
Template Name: Page Concert3 Template
*/
?>
<div class="container">

<div class="row">

	<div class="span8">
		<img src="http://www.themco.ca/wp-content/uploads/2013/10/head27nov13.jpg" width="770" height="455">
	</div>
	<div class="span2">
		<p>.</p>
	</div>

</div><!-- /row -->

<div class="row">

	<div class="span7">
		<h4><div>James Sommerville and Patricia Evans<br>to perform double horn concerto</div></h4>
		<p>James Sommerville has been on our stage before, but not for quite a while. Back in &lsquo;99, Sommerville was just starting out as a horn player and we called him &lsquo;Jamie!&rsquo;</p>
		<p>Now James is the principal horn player for the Boston Symphony Orchestra and Music Director & Conductor of the Hamilton Philharmonic Orchestra. At this concert, we&rsquo;ll see both sides of this accomplished musician.</p>
		<p>Sommerville will conduct the entire concert, will be horn soloist in Mozart&rsquo;s E-flat Major Horn Concerto and will then double up with WSO principal horn player Patricia Evans for a rare treat: Beethoven&rsquo;s Sextet in E-flat for Two Horns.</p>
		<p><b>Karen Sunabacka</b></p>
		<p>We&rsquo;re pleased to be presenting another new work by Winnipeg-born composer Karen Sunabacka. Last season&rsquo;s charming <i>Born by the River</i> was a genuine crowd-pleaser!</p>
		<p>In addition to her work as a composer and cellist, Karen runs a private cello studio and manages a full time teaching load at Providence University College in Otterburne, Manitoba, where she founded the Providence Performing Arts School.</p>

		<div>
			<p>
  			<img src="http://www.themco.ca/wp-content/uploads/2013/01/PreConcert.png"><button id="mcnally" class="btn btn-small btn-inverse" rel="popover" data-placement="top" data-original-title="McNally Robinson event" data-content="At 7:30 pm on Tuesday, November 26th, enjoy a talk with conductor James Sommerville and Karen Sunabacka &mdash; Meet the Composer; McNally Robinson, Grant Park Shopping Centre.">McNally Robinson</button> <button id="preconcert" class="btn btn-small btn-inverse" rel="popover" data-placement="top" data-original-title="Pre-concert event" data-content="Arrive early for more music! Hear a special presentation by University of Manitoba horn students of Patricia Evans; 6:45 pm.">Event</button> <button id="pizza" class="btn btn-small btn-inverse" rel="popover" data-placement="top" data-original-title="Pizza Club" data-content="Book three days in advance for MCO&rsquo;s Pizza Club! Arrive at 6 pm for pizza and a pre-concert presentation, followed by the concert. Tickets are $7.50 for students, including pizza; adults pay regular price. Space is limited; call 204.783.7377 to reserve yours.">Pizza Club</button>
			</p>
		</div>

		<b>The concert begins at 7:30 pm on November 27th in <a href="http://www.westminsterchurchwinnipeg.ca">Westminster United Church</a>, 745 Westminster at Maryland. Tickets are $28 for adults, $26 for seniors and $8 for students, including GST, at <a href="http://www.mcnallyrobinson.com/home" title="McNally Robinson">McNally Robinson</a>, the <a href="http://www.wecc.ca/" title="West End Cultural Centre">West End Cultural Centre</a> (586 Ellice at Sherbrook), <a href="http://www.organicplanet.coop/" title="Organic Planet">Organic Planet</a> (877 Westminster Ave) or MCO's Ticketline (204.783.7377).</b>

		<!-- <div class="media">
					<a class="pull-left" href="#extras" data-toggle="tab">
					<img class="media-object img-circle" src="http://www.themco.ca/wp-content/uploads/2013/01/Don_Anderson_small.jpg">
				</a>
				<div class="media-body">
					<p><strong><a href="#extras" data-toggle="tab">EXTRAS!</strong></a><br />Check out the 'Extras' tab below for Don Anderson&rsquo;s <em>Chamber Chatter</em> article, our <em>Winnipeg Free Press</em> concert review and more!</p>
					<p class="fineprint">&nbsp;<p>
				</div>
				</div> -->
	</div><!-- /span7 -->

	<div class="span1"> 

		<img src="http://retmco-shungite.rhcloud.com/wp-content/uploads/2012/10/BuyTicketsHereHi.png" alt="" width="75" height="150" /><br />
	  	<a href="http://www.1shoppingcart.com/SecureCart/SecureCart.aspx?mid=292CFDD8-2004-4B27-8455-B26B8A4D841F&pid=0a8f7cf1090b49b19275b13665246f64"><img rel="tooltip" title="Click to add adult ticket to cart" data-placement="left" src="http://www.themco.ca/wp-content/uploads/2013/01/AdultC.png" alt="" width="62" height="40" /></a><br />
 	  	<a href="http://www.1shoppingcart.com/SecureCart/SecureCart.aspx?mid=292CFDD8-2004-4B27-8455-B26B8A4D841F&pid=48ce3bbdf64547409a31088955e00c94"><img rel="tooltip" title="Click to add senior ticket to cart" data-placement="left" src="http://www.themco.ca/wp-content/uploads/2013/01/SeniorC.png" alt="" width="62" height="40" /></a><br />
	  	<a href="http://www.1shoppingcart.com/SecureCart/SecureCart.aspx?mid=292CFDD8-2004-4B27-8455-B26B8A4D841F&pid=3a234d6e752643b4a2d5766b474e4d31"><img rel="tooltip" title="Click to add student ticket to cart" data-placement="left" src="http://www.themco.ca/wp-content/uploads/2013/01/StudentC.png" alt="" width="62" height="40" /></a>
		<p class="fineprint">Available August 6th. Click ticket above to add to shopping cart; adjust quantity in cart and return to purchase other types of tickets.</p>

	</div> <!-- /span1 -->

</div><!-- /row -->

<div class="row">

	<div class="span6">

		<div class="well"><!-- tab content well -->

		<ul class="nav nav-pills">
			<li class="active"><a href="#repertoire" data-toggle="tab"><strong>Repertoire</strong></a></li>
			<li><a href="#bios" data-toggle="tab"><strong>Artists</strong></a></li>
			<li><a href="#notes" data-toggle="tab"><strong>Notes</strong></a></li>
			<li><a href="#extras" data-toggle="tab"><strong>Extras</strong></a></li>
		</ul>
		<div class="tab-content">
			<div class="tab-pane fade in active" id="repertoire">
				<p><strong>Manitoba Chamber Orchestra</strong><br>Anne Manson, Music Director<br />Karl Stobbe, Concertmaster<br />Westminster United Church<br>27 November 2013</p>
				<p>James Sommerville, guest conductor and horn soloist<br>Patrica Evans, horn soloist</p>
				<p><b>Witold Lutoslawski</b><br><i>Overture for Strings</i></p>
				<p><b>Karen Sunabacka</b><br>New composition<br>Manitoba Arts Councill commission</p>
				<p><b>Ludwig van Beethoven</b><br>Sextet, in E-flat, for Two Horns and Strings, Op. 81b</p>
				<p><b>Witold Lutoslawski</b><br><i>Musique fun&egrave;bre</i></p>
				<p><b>Wolfgang Amadeus Mozart</b><br />Horn Concerto, in E-flat Major, K370b/371</p>
				<p><b>Le Chevalier de Saint-George</b><br />Symphony in D+</p>
				<p>Concert sponsor / <b>LBL Holdings</b><br>Print media sponsor / <strong><a href="http://www.winnipegfreepress.com/">Winnipeg Free Press</a></strong><br />Radio media sponsors / <strong><a href="http://music.cbc.ca/#/radio2/">CBC Radio 2 98.3</a></strong>, <strong><a href="http://www.cbc.ca/programguide/daily/today/cbc_radio_one">CBC Radio One 990</a></strong>,<br /><strong><a href="http://www.espace.mu/Espace-Musique/">Espace musique 89,9</a></strong> and <strong><a href="http://www.goldenwestradio.com/">Golden West Radio</a></strong>
			</div>
			<div class="tab-pane fade" id="bios">
				<p><b>James Sommerville</b></p>
				<p>James Sommerville is Music Director of the Hamilton Philharmonic Orchestra and Principal Horn of the Boston Symphony Orchestra. Mr. Sommerville has conducted many professional orchestras and ensembles throughout Canada and the USA. He has led the Hamilton Philharmonic to great critical acclaim in his five years as Music Director. Recent engagements include appearances with Symphony Nova Scotia and the Toronto Symphony Orchestra, as well as performances leading the Edmonton, London (Ontario) and Qu&eacute;bec Symphony Orchestras.</p>
				<p>The winner of the highest prizes at the Munich, Toulon and CBC competitions, Mr. Sommerville has pursued a career as a French horn player that has spanned 25 years and brought immensely successful appearances with major orchestras throughout North America and Europe. His disc of the Mozart Horn Concertos with the CBC Vancouver Orchestra won the Juno Award for Best Classical Recording in Canada. Other award-winning CBC recordings include the Britten Serenade for Tenor, Horn, and Strings and Britten&rsquo;s <i>Canticle</i> (with Simon Streatfeild and the MCO). Mr. Sommerville has recorded chamber music for the Deutsche Gramophon, Telarc, CBC, Summit and Marquis labels. He is a member of the Boston Symphony Chamber Players, with whom he tours and records regularly.</p>
				<p>Mr. Sommerville has been a member of the Toronto and Montr&eacute;al Symphony Orchestras, the Canadian Opera Company Orchestra, Symphony Nova Scotia and was acting solo horn of the Chamber Orchestra of Europe. He has toured and recorded extensively as an orchestral player. He is heard regularly on the CBC network and has recorded all of the standard solo horn repertoire for broadcast.</p>
				<p>As a guest artist and faculty member, Mr. Sommerville has performed at many chamber music festivals throughout Canada, the USA, Europe and Japan. Recent solo performances of note include the world premiere of Christos Hatzis&rsquo; <i>Winter Solstice</i> in Yellowknife, NWT, the North American premiere of Ligeti&rsquo;s <i>Hamburg Concerto</i> with the BSO, and the John Williams Horn Concerto. In recent seasons, Mr. Sommerville has appeared as a soloist in London (with the Academy of St. Martin-in-the-Fields), and in Costa Rica, Holland, Québec, Ottawa and Italy. In 2007, he performed the world premiere of Elliot Carter&rsquo;s Horn Concerto, commissioned for him by the Boston Symphony Orchestra. Mr. Sommerville also tours as a member of Osvaldo Golijov&rsquo;s <i>Andalucian Dogs</i>. In April 2010, he stepped in on 48 hours&rsquo; notice to perform Mozart&rsquo;s Horn Concerto No. 2 with Bernard Haitink and the Boston Symphony. In his spare time, Mr. Sommerville enjoys golfing, cycling, eating, running in marathons (including Manitoba&rsquo;s in 2013 when here performing with the Agassiz Chamber Music Festival) and riding his Ducati.</p>
				<p><b>Patricia Evans</b></p>
				<p>A native of northern Vermont, Patricia started playing the horn at 10 years old. She studied at the Oberlin Conservatory of Music and later at McGill University. In 2000, Patricia was awarded a fellowship with the New World Symphony, where she spent the next two years under the baton of Michael Tilson Thomas. In 2002, she won the position of Principal Horn with the Winnipeg Symphony Orchestra. Patricia has been invited to play with some of the top orchestras in North America, including the Montr&eacute;al Symphony, the Saint Louis Symphony, and the National Arts Centre Orchestra. She teaches at the University of Manitoba and can frequently be seen playing with the Winnipeg Chamber Music Society, GroundSwell, and the Manitoba Chamber Orchestra.</p>
				<p><b>Karen Sunabacka</b></p>
				<p>Born in Winnipeg, Karen has been studying music since she was four. She is Assistant Professor in Music Theory and Composition at Providence University College in Otterburne. In March 2008, she graduated from the University of California, Davis, with a PhD in Theory and Composition.</p>
				<p>With her recent orchestral composition <i>And There Was A Great Calm</i>, Karen won the Canadian Music Centre, Prairie Region, Emerging Composers Competition. This piece was then performed at the Winnipeg Symphony Orchestra&rsquo;s New Music Festival in February 2009. </p>
				<p>Karen has also had pieces performed by GroundSwell, the Empyrean Ensemble in Davis (California), the Brandon Chamber Players (Canada), Left Coast Ensemble (San Francisco), Agassiz Chamber Players (Winnipeg), St. Margaret&rsquo;s Anglican Church Choir (Winnipeg), St. Stephen&rsquo;s Episcopal Church in Belvedere (California) and the Vancouver Symphony Orchestra (reading session), conducted by Maestro Bramwell Tovey. She has received commissions from GroundSwell, the Brandon Chamber Players, the Agassiz Chamber Players, St. Margaret&rsquo;s Anglican Church and the Manitoba Chamber Orchestra.</p>
				<p>Karen has presented academic papers about women&rsquo;s voices and electroacoustic music in Paris, Los Angeles and Montreal. Her electronic music has been presented at numerous concerts and festivals including: Cellofest at UCDavis, CNMAT (Center for New Music and Audio Technology) in Berkeley, Merging Voices: Women in New Music Festival in Fullerton, California and at the Electric Rainbow Coalition, an electronic music festival at Dartmouth College in New Hampshire.</p>
				<p>In 2006, Karen won the UCDavis Outstanding Graduate Student Teaching Award and loves teaching music to students of all ages. Her commitment to teaching youth led her to found a Summer Arts Camp in Winnipeg for teens and children; she served as the director for three years. An avid canoeist, she has led and directed many canoe trips and takes much of her inspiration from the outdoors.</p>
			</div>
			<div class="tab-pane fade" id="notes">
				<p><b>Overture for Strings<br>Witold Lutos&#322;awski</b></p>
				<p>Poland&rsquo;s Lutos&#322;awski was one of the most highly respected and widely performed composers of the twentieth century. A careful craftsman with lofty creative standards, he produced a relatively small body of work, some 50 pieces. His orchestral music has proved particularly popular, appearing regularly on the programs of major international symphonies. Many orchestras, such as the Chicago Symphony Orchestra, Royal Philharmonic Orchestra and Los Angeles Philharmonic, commissioned works from him, as did prominent soloists, baritone Dietrich Fischer-Dieskau and violinist Anne-Sophie Mutter among them. He also earned deep respect as a teacher, serving as visiting professor of composition at prestigious institutions in the United States, Scandinavia and Germany. He received numerous awards and prizes, including 16 honorary degrees. Tonight, the MCO pays tribute to him in the centenary year of his birth.</p>
				<p>His life was fraught with difficulties, many of them the result of Europe&rsquo;s tumultuous political life. The First World War forced his family into exile in Russia. In 1918 they returned to Poland, where his musical education began. He made such strong progress that he composed his first music at the age of nine. After a period in which he undertook studies in mathematics, he decided to devote himself completely to music in 1933. Early influences on his creative style include the impressionist works of Claude Debussy, and the effusive post-romanticism of his fellow countryman Karol Szymanowski. Later, the cooler neo-classical style of Stravinsky et al played a significant role in his creative evolution. </p>
				<p>His hope of continuing his education in Paris was dashed by the outbreak of the Second World War. Conscripted into the Polish military&rsquo;s signals and radio unit, he was captured by the Nazis, but escaped and returned to Warsaw. During the war, he eked out a living by playing piano in caf&eacute;s. During the immediate postwar years, he worked for Polish Radio and composed a great deal of straightforward &lsquo;functional&rsquo; music for radio, theatre and film, and for performance by children. He based much of it on Polish folk songs. </p>
				<p>The artistic strictness of Poland&rsquo;s post-war Communist government led to the suppression of individual expression. In parallel with Shostakovich and other composers in the Soviet Union, Lutosławski was forced to continue creating simple, innocuous music for public consumption. He followed his own creative muse through more complex and challenging works that he kept to himself.</p>
				<p>It was only during the post-Stalin thaw of the mid-1950s that he was finally free to follow his personal creative impulses in public. His music earned increasing fame. He also appeared frequently and widely as a conductor of his own works, in part because they called for innovative techniques, including passages of an &lsquo;aleatoric&rsquo; or &lsquo;random/chance&rsquo; nature. This music called for improvisational input from the performers, and its successful performance benefitted strongly from having the composer on the podium.</p>
				<p>Lutos&#322;awski composed the <i>Overture for Strings</i> in 1949, and it was premiered by the Prague Radio Symphony Orchestra on November 9 of that year. It was commissioned by the Swiss conductor Paul Sacher. This enterprising and discerning musician requested an impressive number of works, which have earned the stature of twentieth-century classics, thus playing a significant role in making the chamber orchestra a favoured medium of the period. The list of works he requested included: music by Igor Stravinsky (<i>Concerto for Strings</i>); Richard Strauss (<i>Metamorphosen</i>); Arthur Honegger (Symphonies 2 and 4); Paul Hindemith (<i>Harmony of the World Symphony</i>); Frank Martin (<i>Petite symphonie concertante</i>); and two pieces by B&eacute;la Bart&oacute;k: <i>Music for Strings, Percussion and Celesta</i>, and <i>Divertimento for Strings</i>. In May, the MCO will close the current season with the <i>Divertimento</i>. </p>
				<p>Lutos&#322;awski&rsquo;s <i>Overture</i> is a compact piece containing a great deal of activity and displaying ingenuity in the constant development of its brief thematic material. It presents intricate textures and rapid shifts of mood. Mostly energetic in tone, it contains brief interludes of contrasting tranquility, and numerous brief passages for solo instruments. </p>
				<p><b>Never to Return<br>Karen Sunabacka</b></p>
				<p><i>The composer has written the following note:</i></p>
				<p><i>Never to Return</i> explores the story of my great-great-grandmother, Mathilda Clouston (n&eacute;e Johnson), who was admitted to the Manitoba Asylum (the Selkirk Mental Health Centre) in the 1880s. </p>
				<p>Mathilda was born in Kirkwall, Orkney Islands, Scotland, in 1847. She married Joseph Clouston, an employee of the Hudson&rsquo;s Bay Company, who had traveled back and forth between Orkney and Lower Fort Garry before their marriage. He brought his new bride back to Canada with him in the late 1860s to settle in the Red River Colony, which later became Manitoba.</p>
				<p>Life was hard for these early settlers. In one particularly difficult and disease-stricken winter, two of Mathilda&rsquo;s children died. Unable to dig into the frozen ground, her husband Joseph wrapped the bodies and placed them in the woodshed. Feeling isolated and alone, Mathilda was unable to cope with this loss. She went out to the woodshed and brought her deceased children back into the house, warming them by the fire, insisting that they were not dead. Joseph then took their bodies back to the woodshed. After this happened a number of times, Joseph committed her to the Manitoba Asylum, where she would spend the rest of her life.</p>
				<p>Never to Return explores Mathilda&rsquo;s life through three Scottish melodies. The first melody I use is a fiddle tune titled <i>Da Bride&rsquo;s a Bonnie Ting</i>. Through research, I found that this tune was played at Orkney weddings during the nineteenth century. Although altered rhythmically, the melody forms the basis of the first and most consonant section of the piece. I use the tune to depict the happiness of Mathilda&rsquo;s wedding day and her happy memories of life on Orkney. </p>
				<p>The second melody is an &lsquo;air&rsquo; from the book <i>Ancient Orkney Melodies</i>, compiled by Colonel David Balfour of Balfour and published in 1885. The air is called <i>The Braid, Braid Sea</i> but Balfour adds his own words about a woman he meets &ldquo;on the Ness of Stromness.&rdquo; She had lost her mind because of the death of her lover at sea and so wanders on the beach collecting seaweed. I thought the story and the air had a haunted quality that fit Mathilda&rsquo;s descent into mental illness. This melody is used in the middle of the piece and is the hardest to hear as it depicts pain, suffering and Mathilda’s loss of reality. </p>
				<p>The final melody I use is a traditional Scottish melody titled <i>Ye Banks and Braes</i>. It is common and can be found in a number of books, recordings and YouTube videos. The original text is by Robert Burns. I also found a sacred modern version arranged by John Bell and Graham Maule. Both versions of the text are about love, pain and loss. The modern version also talks about healing and faith. Ending the piece with this tune is how I want to complete Mathilda&rsquo;s story &mdash; with healing and hope. Even though Mathilda never left the Mental Health Centre, I hope that she found some peace, but she ultimately left her suffering behind through her own death.</p>
				<p><i>Never to Return</i> is a kind of lament &mdash; the cry of Mathilda, whose mind was broken by the loss of her children. Her loss and sacrifices gave me life. Her story is part of my story and our story. Giving voice to her pain, her suffering, and to her sacrifices is a way for me to reconcile her story with my own and the history of the early Manitoba settlers.</p>
				<p><b>Sextet in E-flat Major, Op. 81b for two horns and strings<br>Ludwig van Beethoven</b></p>
				<p>Beethoven&rsquo;s string quartets are without doubt his greatest pieces of chamber music, and possibly the finest of all works in the genre. On occasion, he used four strings in combination with other instruments, as in this sextet. Here their function is different. What we have is, in effect, a concerto for two solo horns with string quartet accompaniment. It may not occupy the same lofty and inspiring creative plateau as the string quartets, but it is nevertheless an effective and most enjoyable work. </p>
				<p>Despite the high opus number, it predates all his string quartets. The most likely date of composition is 1794/95, three years after his relocating from Bonn to Vienna, and three years before the publication of his first quartets, the six pieces that make up Opus 18. </p>
				<p>The manuscript of the sextet has disappeared, but a German musicologist, Gustav Nottebohm, possessed the first horn part. Beethoven had inscribed on it the words &ldquo;Sextet by me. God knows where the other parts are!&rdquo; He had received instruction on writing for the horn from a professional performer, Nicolas Simrock. In 1810, Beethoven sent the manuscript to Simrock, who by that time had traded playing music for publishing it. Beethoven included the following note: “The pupil has given the master many a hard nut to crack.” The sextet&rsquo;s numerous technical challenges for the horns reinforce the aptness of his message. </p>
				<p>It offers a truly harmonious blend of instrumental colours, within a civilized, Haydn-esque style. Just a few years before composing this piece, Beethoven had completed his single year of study with that older, established master. He had planned on more, but the two giants of music simply did not get along. </p>
				<p>Given the horn&rsquo;s history, the regular appearance of hunting-style themes and rhythms in the sextet &mdash; particularly in the lively outer movements &mdash; was a given. In those same sections, Beethoven regularly called upon the horns to explore both the high and the low extremes of their registers, and to perform solo and duet passages. The second movement is an exceptionally beautiful interlude of repose. Eloquence is everywhere to be heard, including via the cello. </p>
				<p><b>Musique fun&egrave;bre (Music of Mourning) for strings<br>Witold Lutos&#322;awski</b></p>
				<p>Lutos&#322;awski composed this work from 1954 to 1958, in the immediate wake of the piece that led to his being considered Poland&rsquo;s finest living composer: the <i>Concerto for Orchestra</i>. Polish conductor Jan Krenz asked him to compose a piece to mark the tenth anniversary of the death of the distinguished Hungarian composer, B&eacute;la Bart&oacute;k. The premiere of <i>Music of Mourning</i> was given in Katowice in March 1958, and it brought Lutos&#322;awski his first major international success.</p>
				<p>Free at last from all politically-imposed creative restraints, he considered it &ldquo;my first word in a new language.&rdquo; The opening section surges forth on a wave of bleak emotion and dark string colours. The following section, introduced by pizzicato playing, and featuring a series of sharp, buzzing tremolos, begins in defiance and progresses to rage. After a searing climax, the music unwinds gradually to end with a totally spare texture and an atmosphere of utter desolation. </p>
				<p><b>Horn Concerto in E-flat Major, K. 370b/371<br>Wolfgang Amadeus Mozart (arr. Robert D. Levin)</b></p>
				<p>Research has shown that Mozart composed all or part of six horn concertos. Only three of them have survived in their full, original forms, and the rest of the materials exist in various incomplete states. Most of them came into being because of his friendship with the horn player Joseph (Ignaz) Leutgeb. They had known each other since the time Leutgeb played in the court orchestra in Mozart&rsquo;s home town, Salzburg. He became one of the closest friends Mozart had during his formative years. When Mozart and his father Leopold traveled to Italy in 1772/73, Leutgeb went with them, and caused a sensation with his spectacular and sensitive playing. </p>
				<p>Leutgeb settled in Vienna in 1777. His name is listed as first horn for that city&rsquo;s court and national theatre orchestras. Unable to make a living through his playing alone, he took over his father-in-law&rsquo;s tiny cheese shop with money borrowed from Leopold Mozart. His retail income allowed him to continue making solo appearances. He was slow in paying back the loan, however, a situation from which Mozart was obliged to rescue him. &ldquo;Please have a little patience with poor Leutgeb,&rdquo; Mozart wrote to his father. &ldquo;If you knew his circumstances and saw how he has to muddle along, you would certainly feel sorry for him. I shall have a word with him and I feel sure that he will pay you, at any rate by instalments.&rdquo;</p>
				<p>Mozart and Leutgeb must have shared a pointed sense of humour, since the manuscripts of the horn concertos are laced with affectionate insults aimed at the soloist. For example, Mozart prefaced the score of the concerto, K. 417, with the following words: &ldquo;Wolfgang Amadeus Mozart has taken pity on Leutgeb, ass, ox, and fool, in Vienna on 27 May 1783.&rdquo; And in the finale of the Concerto in D Major, the orchestra part is marked Allegro (fast), but the soloist&rsquo;s part is marked Adagio (slow), a comment on Leutgeb&rsquo;s habit of playing behind the beat. Mozart&rsquo;s inscriptions continue with &rsquo;Take it easy &mdash; for you, Signor Ass &mdash; come on &mdash; good for you &mdash; get it over with &mdash; how flat you play &mdash; catch your breath &mdash; finished? Thank heavens! &mdash; enough, enough!&rdquo; Caustic comments aside, Mozart&rsquo;s horn concertos are heavenly pieces. They demonstrate that Leutgeb must have been an agile and poetic performer.</p>
				<p>Leutgeb asked Mozart for a concerto as early as 1777, but the first fragment of one to appear was the cheerful Rondeau, K. 371, which Mozart composed in March 1781. It was the first work he composed in Vienna, where he had happily relocated from Salzburg, the home town that he despised. He wrote out the complete solo horn line of the Rondeau, but orchestrated only the first page. Several performing versions have been prepared. At this concert you will hear an edition created by the distinguished American musicologist and keyboard soloist, Robert D. Levin. It incorporates 60 bars of music that were rediscovered and added back just 25 years ago. </p>
				<p>Preceding it at this evening&rsquo;s concert is the other horn concerto fragment from that same period. It is a bare sketch for what appears to be an opening movement, perhaps for the same abandoned concerto for which Mozart probably intended the Rondeau, K. 371 to be the finale. It exists in a state that is even more fragmentary than that of the Rondeau. You will hear this moderately paced, most gracious yet quite demanding music in a version prepared by Robert D. Levin. </p>
				<p>When Mozart died, Leutgeb stated that he didn&rsquo;t know anything about a two-movement horn concerto &mdash; possibly because Mozart hadn&rsquo;t written it for him. The incomplete manuscript survived until 1856, the centenary of Mozart&rsquo;s birth. His son, Carl Thomas, cut it up with scissors and gave the pieces as gifts to musicians who had taken part in the one hundredth anniversary celebrations. </p>
				<b>Symphony in D Major, Op. 11 No. 2<br>Joseph Boulogne, Chevalier de Saint-George</b>
				<p>Sometimes referred to as &lsquo;The Black Mozart,&rsquo; after his great contemporary, Saint-George was born on Basse Terre, one of two mid-Atlantic islands that make up Guadeloupe. They had been colonized by France. His father, George Boulogne, was a wealthy plantation owner, and his mother was George&rsquo;s African slave, Nanon. The Chevalier&rsquo;s friend Henry Angelo described her as &ldquo;Africa&rsquo;s most beautiful gift to France.&rdquo; </p>
				<p>At that time, the normal fate of a bi-racial child would have been slavery, but baby Joseph escaped it. Since the discriminatory laws of the day didn&rsquo;t allow him to adopt his father&rsquo;s last name, he was called Saint-George, after a handsome ship that was anchored off the coast of Guadeloupe.</p>
				<p>In 1753, the family moved to France, where Joseph received an education worthy of an aristocrat, at the Royal Academy of Arms. Years before his great musical gifts made themselves apparent, he found recognition through sports. Fencing headed the list, but he also fared brilliantly with riding, skating, swimming, running, target shooting &mdash; and dancing. He would continue fencing at an international level for the remainder of his life. When he graduated at age 19, he was dubbed Chevalier and seemed destined for a military career. </p>
				<p>His early musical training is unclear, but after he arrived in France he probably studied composition with François-Joseph Gossec, one of the leading French composers of the day, and violin with either the illustrious Jean-Marie Leclair or Antonio Lolli. Surely wielding a violin bow and a rapier call for much the same skills! Due to his elegant manners, physical prowess, appearance (including his six-foot-plus height) and dazzling musicianship, he became a much sought-after figure in the aristocratic salons of Paris. Henry Angelos wrote that &ldquo;Saint-George combined in his person his mother&rsquo;s grace and good looks and his father&rsquo;s vigour and assurance.&rdquo;</p>
				<p>In 1769, Saint-George joined Gossec&rsquo;s orchestra, the <i>Concert des Amateurs</i>, and was quickly promoted to concertmaster. Three years later he made his debut as a violin soloist, performing one of his own concertos. According to the newspaper Mercure, it received &ldquo;the most rapturous applause, both for its excellent execution and for the composition itself.&rdquo;</p>
				<p>In the wake of his father&rsquo;s death two years later, the generous annuity he had been paying his son ceased, and Saint-George was required to earn his own living for the first time. He made a good income from his musical activities but, in another parallel with Mozart, he still found himself in shaky financial territory on several occasions.</p>
				<p>In 1775, his friend, Queen Marie-Antoinette, proposed that he become co-music director of the prestigious Paris Opéra, but a petition sent by three female members of that company led to his nomination being withdrawn. It stated that &ldquo;their honour and the delicate nature of their conscience made it impossible for them to be subjected to the orders of a mulatto.&rdquo;</p>
				<p>In 1781 he founded a new orchestra, the Concert de la Loge Olympique. It came to be considered one of the finest ensembles in Europe. It was also the largest, sporting 40 violins, 10 double basses and matching ranks of virtuoso wind players (totaling more members than many full modern orchestras!). The musicians decked themselves out with chic costumes to match their reputation. They performed wearing dashing sky-blue dress coats, swords swinging from their waist-bands. </p>
				<p>Saint-George showed exceptional taste in commissioning new music for this orchestra. He played a major role (together with the Comte d&rsquo;Ogny) in securing six symphonies from Joseph Haydn. The result was the superlative &lsquo;Paris&rsquo; Symphonies, No. 82 to 87. They were premiered during the orchestra&rsquo;s 1787 season, under the direction of Saint-George. </p>
				<p>He spent the final decade of his colourful life travelling between France and England, and participating more in politics than music. He became embroiled in various revolutionary plots and counter-plots. During the revolution of 1789 he joined the National Guard, and was later named the colonel of a thousand-strong troop of black soldiers. A victim of the reign of terror that followed the revolution, he spent 18 months in a military prison. In his final years, he founded and directed another Parisian orchestra, the Cercle de l&rsquo;harmonie. </p>
				<p>He composed well over 200 works. The published pieces included symphonies, violin concertos, examples of the popular hybrid form, the symphonie concertante, operas and chamber works. His only two symphonies were published in 1799 as Opus 11. The number is decreased to one since No. 1 appears to be spurious. He used No. 2 as both a concert work and the overture to his comic opera-ballet <i>L&rsquo;amant anonyme</i> (The Anonymous Lover, 1780). The first movement is bright and lively, with a slightly shadowy opening to the central section. The slow second movement is attractive but rather troubled in emotional terms. A cheerful, vigorous finale concludes the symphony. </p>
			</div>

			<div class="tab-pane fade" id="extras">
				<section class="row">
 					<div class="span5">
 						<div class="flex-video widescreen">
 							<iframe width="510" height="287" src="http:////www.youtube.com/embed/poqRot3A2Mc" frameborder="0" allowfullscreen seamless></iframe>
 							<p>Posted to <a href="http://www.youtube.com"><b>youtube.com</b></a> by the <a href="http://www.bso.org/"><b>Boston Symphony Orchestra</b></a>: &lsquo;It's your BSO: Exclusive interview with James Sommerville, Principal French Horn.&rsquo;</p>
 							<p>&nbsp;</p>
 						</div>
 					</div>
				</section>
			</div>


		</div><!-- /tab-content -->

		</div><!-- /tab content well -->

	</div><!-- /span6 tab area -->

	<div class="span2 offset1">
		<p class="fineprint">.</p>
	</div>

</div><!-- /row -->

<?php get_template_part('templates/content', 'concert'); ?>

</div><!-- /container -->
