<?php
/*
Template Name: Page Concert5 Template
*/
?>
<div class="container">

<div class="row">

	<div class="span8">
		<img src="http://www.themco.ca/wp-content/uploads/2013/01/head19feb13.jpg" alt="" width="770" height="455">
	</div>
	<div class="span2">
		<p>.</p>
	</div>

</div><!-- /row -->

<div class="row">

	<div class="span7">
		<h4>Janina Fialkowska has played<br />a big part in the MCO&rsquo;s 40-year story</h4>
		<p>Some of MCO&rsquo;s guest soloists become more like family, and that definitely includes Canadian pianist Janina Fialkowska. It’s been a while since she has graced our stage, and a fortieth birthday seems like the perfect occasion to get together!</p>
		<p>Fialkowska has been in the news quite a bit lately, both for receiving the Governor General’s Performing Arts Award and with glowing reviews of her new album, Liszt Recital (named album of the week by <em>The Independent</em>). In Gramophone, reviewer Bryce Morrison exclaimed, &ldquo;We need many more records from this master-pianist!&rdquo;</p>
		<p><strong>Lifetime achievement</strong></p>
		<p>Janina Fialkowska received Canada&rsquo;s 2012 &lsquo;Governor General&rsquo;s Performing Arts Award&rsquo; for Lifetime Achievement in Classical Music. Three days of celebration included a reception on Parliament Hill and a private luncheon with the Speaker of the House of Commons.</p>
		<p>At the official ceremony in Rideau Hall, thousands cheered and there were heartfelt contributions from fellow pianist Jackie Parker and from Oscar-winning (friend, cousin and Connecticut neighbour) Christopher Plummer, as well as a very personal and moving tribute from Canadian radio icon and friend Shelagh Rogers.</p>

		<div>
			<p>
  			<img src="http://www.themco.ca/wp-content/uploads/2013/01/PreConcert.png"><button id="preconcert" class="btn btn-small btn-inverse" rel="popover" data-placement="top" data-original-title="Pre-concert event" data-content="Arrive early for more music! Hear a sneak preview of &lsquo;Brundib&aacute;r&rsquo; by the Pembina Trails Voices choir; under the direction of Ruth Wiwchar; 6:45 pm.">Event</button> <button id="pizza" class="btn btn-small btn-inverse" rel="popover" data-placement="top" data-original-title="Pizza Club" data-content="Book three days in advance for MCO&rsquo;s Pizza Club! Arrive at 6 pm for pizza and a pre-concert presentation, followed by the concert. Tickets are $7.50 for students, including pizza; adults pay regular price. Space is limited; call 204.783.7377 to reserve yours.">Pizza Club</button> <button id="mcnally" class="btn btn-small btn-inverse" rel="popover" data-placement="top" data-original-title="McNally Robinson event" data-content="On Monday, February 18th, hear a special presentation with MCO Music Director and Conductor Anne Manson and composer Karen Sunabacka; McNally Robinson, Grant Park Shopping Centre.">McNally Robinson</button>
			</p>
		</div>

		<strong>The concert begins at 7:30 pm on February 19th in <a href="http://www.westminsterchurchwinnipeg.ca">Westminster United Church</a>, 745 Westminster at Maryland. Tickets are $26.50 for adults, $24.50 for seniors and $7.50 for students, including GST, at <a href="http://www.mcnallyrobinson.com/home" title="McNally Robinson">McNally Robinson</a>, the <a href="http://www.wecc.ca/" title="West End Cultural Centre">West End Cultural Centre</a> (586 Ellice at Sherbrook), <a href="http://www.organicplanet.coop/" title="Organic Planet">Organic Planet</a> (877 Westminster Ave) or MCO's Ticketline (783-7377).</strong>
		<p class="fineprint">&nbsp;<p>
	</div><!-- /span7 -->

	<div class="span1"> 
		<img src="http://retmco-shungite.rhcloud.com/wp-content/uploads/2012/10/BuyTicketsHereHi.png" alt="" width="75" height="150" /><br />
	  <a href="http://www.1shoppingcart.com/SecureCart/SecureCart.aspx?mid=292CFDD8-2004-4B27-8455-B26B8A4D841F&pid=91b27cbe6bf64a1b8244f6289f5273d3"><img rel="tooltip" title="Click to add adult ticket to cart" data-placement="left" src="http://www.themco.ca/wp-content/uploads/2013/01/AdultC.png" alt="" width="62" height="40" /></a><br />
 	  <a href="http://www.1shoppingcart.com/SecureCart/SecureCart.aspx?mid=292CFDD8-2004-4B27-8455-B26B8A4D841F&pid=d54722441d95415db11ae848b79d5583"><img rel="tooltip" title="Click to add senior ticket to cart" data-placement="left" src="http://www.themco.ca/wp-content/uploads/2013/01/SeniorC.png" alt="" width="62" height="40" /></a><br />
	  <a href="http://www.1shoppingcart.com/SecureCart/SecureCart.aspx?mid=292CFDD8-2004-4B27-8455-B26B8A4D841F&pid=743f6309b592497c81325e9b16f06e23"><img rel="tooltip" title="Click to add student ticket to cart" data-placement="left" src="http://www.themco.ca/wp-content/uploads/2013/01/StudentC.png" alt="" width="62" height="40" /></a>
		<p class="fineprint">Click ticket above to add to shopping cart; adjust quantity in cart and return to purchase other types of tickets.</p>
	</div><!-- /span2 -->

</div><!-- /row -->

<div class="row">

	<div class="span6">

		<div class="well"><!-- tab content well -->

		<ul class="nav nav-pills">
			<li class="active"><a href="#repertoire" data-toggle="tab"><strong>Repertoire</strong></a></li>
			<li><a href="#bios" data-toggle="tab"><strong>Artists</strong></a></li>
			<li><a href="#notes" data-toggle="tab"><strong>Notes</strong></a></li>
			<li><a href="#extras" data-toggle="tab"><strong>Extras</strong></a></li>
		</ul>
		<div class="tab-content">
			<div class="tab-pane fade in active" id="repertoire">
				<p><strong>Manitoba Chamber Orchestra</strong><br />Anne Manson, Music Director and Conductor<br />Karl Stobbe, Concertmaster<br />Westminster United Church<br />19 February 2013</p>
				<p>Janina Fialkowska, piano</p>
				<p><strong>Karen Sunabacka</strong><br /><i>Born by the River</i><br />Manitoba Arts Council commission</p>
				<p><strong>Wolfgang Amadeus Mozart</strong><br />Piano Concerto, No. 12, in A Major, K 414</p>
				<p><strong>Gary Kulesha</strong><br /><em>String Serenade</em></p>
				<p><strong>Franz Joseph Haydn</strong><br />Symphony No. 82, in C major, Hob. 1/82 (The Bear)</p>
				<p>Piano sponsors / <strong><a href="http://www.stjohnsmusic.com/splash">St. John's Music</a></strong> and <strong><a href="http://ca.yamaha.com/en/products/musical-instruments/">Yamaha Canada</a></strong><br />Season sponsor / <strong><a href="http://www.greatwestlife.com/001/Home/index.htm">The Great-West Life Assurance Company</a></strong><br />Print media sponsor / <strong><a href="http://www.winnipegfreepress.com/">Winnipeg Free Press</a></strong><br />Radio media sponsors / <strong><a href="http://music.cbc.ca/#/radio2/">CBC Radio 2 98.3</a></strong>, <strong><a href="http://www.cbc.ca/programguide/daily/today/cbc_radio_one">CBC Radio One 990</a></strong>,<br /><strong><a href="http://www.espace.mu/Espace-Musique/">Espace musique 89,9</a></strong> and <strong><a href="http://www.goldenwestradio.com/">Golden West Radio</a></strong>
			</div>
			<div class="tab-pane fade" id="bios">
				<p><strong>Janina Fialkowska</strong></p>
				<p>Beloved worldwide for her exquisite pianism, Janina Fialkowska has enchanted audiences for over thirty years with her glorious lyrical sound, her sterling musicianship and her profound sense of musical integrity. Born in Montréal to a Canadian mother and a Polish father, Janina studied in Montréal, Paris and at Juilliard and her career was launched in 1974 by Arthur Rubinstein after her prize-winning performance at his inaugural Master Piano Competition in Israel. She has since performed with all the foremost US, Canadian, European and Asian orchestras &mdash; many of them numerous times &mdash; working with conductors such as  Sir Georg Solti, Sir Andrew Davis, Bernard Haitink, Lorin Maazel, Zubin Mehta, Stanislaw Skrowaczewski and Klaus Tennstedt.</p>
				<p>Janina Fialkowska has won special recognition for a series of important premieres, most notably the world premiere performance of a newly discovered piano concerto by Liszt with the Chicago Symphony in 1990 and, in 2010, with the Québec Symphony Orchestra the world premiere of the Chopin-inspired piano concerto entitled <em>Prelude Variations</em> by John Burge &mdash; written for and dedicated to Janina. Adding to her already significant discography, in 2010 Ms. Fialkowska released three CDs of Chopin&rsquo;s music, all of which received stellar reviews worldwide. &ldquo;Indeed, lesser mortals may well weep with envy at such unfaltering authority.&rdquo; (Bryce Morrison in Gramophone Magazine about the pianist&rsquo;s double album Chopin: Etudes, Impromptus, Sonatas.)</p>
				<p>Janina Fialkowska was the Founding Director of the hugely successful Piano Six project and its successor, Piano Plus. This latest project brings together some of Canada&rsquo;s greatest classical pianists, instrumentalists and vocalists with Canadians who, for either geographical or financial reasons, would otherwise be unable to hear this calibre of live classical performance. In 2000, Piano Six won a top Canadian Arts award &mdash; the Chalmers.</p>
				<p>In January 2002, at the onset of a major European tour, Ms. Fialkowska&rsquo;s career was brought to a dramatic halt by the discovery of a tumour in her left arm. After successful surgery to remove the cancer, Janina underwent further surgery a year later &mdash; a rare muscle-transfer procedure. After 18 months of performing the Ravel and Prokofiev concertos for Left Hand (which she transcribed for her right hand) she resumed her two-handed career, beginning with a tremendously successful and highly emotional recital held in Germany in January 2004.</p>
				<p>2011 was Liszt&rsquo;s anniversary year and Janina celebrated it on concert stage and on CD. Her latest CD release, Liszt Recital, was hailed as &ldquo;the most beautiful Liszt CD of this decade&rdquo; (Frankfurter Allgemeine Zeitung). She also shared her Liszt expertise in several master classes around the world, including at her own International Piano Academy in Bavaria and at the Schleswig Holstein Music Festival. Her 2011 performances included her debut with the Radiosinfonieorcester Stuttgart, her Swiss debut with Musikkollegium Winterthur and the opening concert of the international Singapore Piano festival.</p>
				<p>Janina Fialkowska is an Officer of the Order of Canada and holds honorary doctorates from Acadia University and Queen&rsquo;s University. She received the 2012 Governor General&rsquo;s Performing Arts Award for Lifetime Achievement in Classical Music &mdash; Canada&rsquo;s foremost honour for excellence in the performing arts.</p>
				<p><strong>Karen Sunabacka</strong></p>
				<p>Karen Sunabacka&rsquo;s music has been performed in Canada, the US and the United Kingdom. In April 2010 she was the featured composer for the Eckhardt-Gramatté National Music Competition where nine young pianists each performed her commissioned piece Curlicue. Karen won the Canadian Music Centre, Prairie Region, Emerging Composers Competition in February 2009 with her orchestral composition And There Was A Great Calm. </p>
				<p>Karen has also had pieces performed by GroundSwell, the Empyrean Ensemble in Davis (California), the Brandon Chamber Players, Left Coast Ensemble (San Francisco), Agassiz Chamber Players, St. Margaret&rsquo;s Anglican Church Choir (Winnipeg), St. Stephen&rsquo;s Episcopal Church in Belvedere (California) and the Vancouver Symphony Orchestra (reading session) conducted by Maestro Bramwell Tovey.</p>
				<p>As a professor Karen has presented academic papers about women&rsquo;s voices and electroacoustic music all over the world, but most notably in Paris, Los Angeles and across Canada. Her electronic music has been presented at numerous concerts and festivals including: Cellofest at UCDavis, Center for New Music and Audio Technology in Berkeley, Merging Voices: Women in New Music Festival in Fullerton, California and at the Electric Rainbow Coalition, an electronic music festival at Dartmouth College in New Hampshire.</p>
				<p>In 2006 Karen won the prestigious UCDavis Outstanding Graduate Student Teaching Award and loves teaching music to students of all ages. Her commitment to teaching has led to many new projects including Summer Arts Camps, composers&rsquo; workshops and community music programs. She has led and directed many canoe trips and finds much of her inspiration from the outdoors.</p>
				<p>Karen was born in Winnipeg in 1975. In March 2008 she graduated from the University of California, Davis with a PhD in Theory and Composition. As a composer, &lsquo;cellist and university professor she is often juggling chamber music performances, composition and a full university teaching load along with a private cello studio. She is the director and founder of the Providence Performing Arts School and she is the Assistant Professor in Music Theory and Composition at Providence University College in Otterburne, Manitoba.</p>
				<p><strong>Gary Kulesha</strong></p>
				<p>Gary Kulesha, who is on Toronto University&rsquo;s Faculty of Music, is one of Canada&rsquo;s most visible musicians. Although principally a composer, he is also active as a pianist, conductor and teacher. His music has been commissioned, performed and recorded by musicians and ensembles the world over. Angels, for marimba and tape, has become a standard repertoire item for percussionists, while his works for Danish recorder virtuoso Michala Petri are toured by her throughout the world each year. Works such as Mysterium Coniunctionis and the Sonata for Horn, Tuba and Piano are performed regularly in Europe and are often taught there as part of performance curricula. Mr. Kulesha&rsquo;s first opera Red Emma, was included in Opera Canada&rsquo;s book of &ldquo;Operas which should be performed more often,&rdquo; beside works by Copland, Bernstein and Weill.</p>
				<p>Gary Kulesha has spent many years as Composer-in-Residence with both the Kitchener-Waterloo Symphony and the Canadian Opera Company and in 1995 was appointed Composer-Advisor to the Toronto Symphony Orchestra. In 2002 he was one of three composers awarded the first National Arts Centre Orchestra Composer Award. This began an extended relationship with the NACO and Pinchas Zukerman, which has included touring with them and writing several works for them.</p>
				<p>An active supporter of young composers and performers, Gary Kulesha was the Artistic Director of The Composers&rsquo; Orchestra from 1987, stepping down in 2004 in favour of three young composers. His conducting activities are extensive and he has premiered hundreds of works. He has guest conducted frequently with major orchestras throughout Canada, and has recorded for radio and CD. Although he is well-known as a specialist in 20th century music his repertoire ranges from little-known Baroque music through to the music of our time. He is currently assisting Toronto Symphony Music Director Peter Oundjian with the design and programming of the TSO&rsquo;s New Creations Festival.</p>
			</div>
			<div class="tab-pane fade" id="notes">
				<p><strong>Born by the River<br />Karen Sunabacka</strong></p>
				<p><em>The composer has provided the following note:</em></p>
				<p><i>Born by the River</i> is a piece in which I explored my Manitoba heritage through the visual art, music and stories of my M&eacute;tis grandmother, Lenore Clouston (n&eacute;e Birston). My grandmother (on my mother&rsquo;s side) was born by the Red River in the Selkirk area.</p>
				<p>Lenore Clouston was a farmer, visual artist, and local community activist. She came of age during World War Two when her own family&rsquo;s aboriginal roots were hidden; her grandmother spoke Cree, but this was not talked about. Through her art she explored her multicultural past so that her children and the following generations could be proud of their heritage.</p>
				<p>My grandmother met my Scottish grandfather in a band where he played fiddle and she played piano. As a child, I spent much time at my grandparents farm near Selkirk, and the highlights were the times my grandparents performed together. My grandmother&rsquo;s rhythmic chords laid the foundation for the pieces, and she would often sing and laugh as she banged the chords out on the piano. I remember dancing the night away with my siblings as the music twirled around us. For a few years, I also learned some fiddle tunes myself and played with my grandparents. For this reason it is the M&eacute;tis music of the Red River Valley that is the background of this piece as it brings together this multicultural past. The fiddle tunes show up in fragments and they are the major rhythmic pulse throughout the work.</p>
				<p>The other musical material in the piece comes from my grandmother&rsquo;s first name &mdash; Lenore. I divided the letters of her name into the following three syllables: Le No Re. To figure out a pitch equivalent to these three syllables, I drew upon my experience as a teacher. When teaching students to read music I use the Solfege system, which uses syllables to teach pitches (Do-Re-Mi ... etc &mdash; similar to how Maria teaches the Von Trapp children in <i>The Sound of Music</i>). In this system, &lsquo;Le&rsquo; can be reinterpreted at the pitch A-flat. The syllable &lsquo;No&rsquo; does not have a pitch equivalent in this system, so I interpreted it as a pitch-less or bow-less note (pizzicato) followed by silence. In other words the &lsquo;No&rsquo; sections and notes are without something and include more silence. The final part of my grandmother&rsquo;s name, &lsquo;Re,&rsquo; is also a syllable from the Solfege system and can be reinterpreted as the pitch D. So together, the Lenore motive is: A-flat, no pitch / silence, D. This motive is both in the larger structure of the piece and in the foreground as small three-note motives.</p>
				<p>During the Depression, my grandmother and her family lost their river plot near Selkirk and moved a few miles west. However, the Red River and the old family homestead continued to be an important source of artistic inspiration for my grandmother. In preparation for composing this piece, I read her poems and prose, and I looked at some of her paintings and drawings that depicted her early childhood by the Red River. Because of my grandmother&rsquo;s love for this waterway, <i>Born by The River</i> also depicts the water&rsquo;s movement through the constant rhythms that weave in and around the Lenore motive. The music moves around the Lenore motive similar to the way the Red River meandered around my grandmother throughout her life.</p>
				<p><strong>Piano Concerto No. 12 in A Major, K 414<br />Wolfgang Amadeus Mozart</strong></p>
				<p>Mozart launched his life as a freelance artist in Vienna in May 1781. Since he was best known there as a pianist, he composed numerous piano works to play at his own subscription concerts. Among them are three concertos, his first such works created in Vienna. He intended to perform them in a concert series during the early months of 1783.</p>
				<p>They may not be quite as marvellous as the further set of 12 which he wrote between 1784 and 1786, but Concertos 11, 12 and 13 are thoroughly engaging works. Although the A Major was published as No. 12, it was probably the first in order of composition, and the most likely time period was the autumn of 1782. Unfortunately for Mozart, the intended series was under-subscribed and only one of the advertised concerts took place. No. 12 may have received its premiere on that occasion.</p>
				<p>Mozart described the three concertos in a letter to his father, Leopold as &ldquo;a happy medium between what is too easy and too difficult; they are very brilliant, pleasing to the ear and natural, without being vapid. There are passages here and there from which connoisseurs alone can derive satisfaction; but these passages are written in such a way that the less learned cannot fail to be pleased, though without knowing why.&rdquo; He let it be known that all three could be performed either as a concerto with orchestra, or in more intimate settings, such as a home or an aristocratic salon, as a quintet for piano and strings.</p>
				<p>The first movement of No. 12 presents a steady flow of attractive themes in an easy-going and graceful manner. The second movement is unusually poignant, due at least in part to possible extra-musical considerations. It is based on a theme from the opera <em>La calamità dei cuori</em> by Johann Christian Bach, whom Mozart had come to know and love during a boyhood visit to London. Bach died in January 1782. Mozart may have conceived this movement as a tender, heartfelt adieu. He concludes the concerto with a rondo that is every bit as relaxed and genial as the opening movement.</p>
				<p><strong>Serenade for String Orchestra<br />Gary Kulesha</strong></p>
				<p><em>The composer has provided the following note:</em></p>
				<p>My Serenade for String Orchestra was commissioned by the Canadian Broadcasting Corporation for the Manitoba Chamber Orchestra, and premiered by the MCO on 27 November 1985, at the Winnipeg Art Gallery, with Simon Streatfeild conducting. It was revised extensively during September and October of 1986.</p>
				<p>During 1985, I had the opportunity to write two works which reflect my love for the music which I grew up with. Like most musicians, I first learned music through the great repertoire, and I have never lost my affection for these pieces. When Randy Barnard of the CBC in Winnipeg asked me to write a work for the MCO, I took it as an opportunity to write a large string piece which, in effect, pays homage to the great string pieces I know and love, like the Tchaikovsky Serenade, the Vaughan Williams Fantasia on a Theme by Thomas Tallis, and the Barber Adagio. Although I did not in any way copy these works, I hope their spirit is reflected in my Serenade.</p>
				<p>This music relies somewhat less on atonality than most of my work up to and since this piece, but I hope that it contains some recognizable &lsquo;fingerprints&rsquo; of my style. And although the overall aim of the piece is as traditional as the intent of my models for it, I have attempted to blend certain elements into the language which are unthinkable in any of the earlier works, including tone clusters, pattern music, and certain elements of popular music.</p>
				<p>I was dissatisfied with the original first movement of the Serenade, and, with the encouragement of David Keeble of the CBC in Ottawa, I undertook to re-write it in the fall of 1986. Essentially, the first movement became two separate movements, with some material getting cut entirely, and a great deal of new material being added. This sort of revision is often difficult and unrewarding work &mdash; it was unusually difficult in this case, as I had returned to a much more atonal language between the original work and the re-write. Much to my surprise and pleasure, what has emerged is a stronger work, now in four movements instead of the original three.</p>
				<p><strong>Symphony No. 82<br />in C Major &mdash; &lsquo;The Bear&rsquo;<br />Joseph Haydn</strong></p>
				<p>During Haydn&rsquo;s first 30 years as director of music to the aristocratic Esterházy family, he remained a virtual prisoner on their estates, in and around Vienna. His music travelled for him, however (as he himself would, following the death of Prince Nikolaus Esterházy in 1790). One centre where it had become exceptionally popular was Paris, where his symphonies had been performed as early as the 1760s. In 1785, the Concert de la Loge Olympique, one of the city&rsquo;s most prestigious musical organizations, commissioned six new symphonies from him. Reflecting the continent-wide reputation as the master of symphonic composition he had earned by that time, they offered him five times their usual fee: 25 louis d&rsquo;or each, plus a further five for the publishing rights (this translates to about sixty thousand dollars per symphony in modern currency).</p>
				<p>Haydn composed the pieces which have become known (due to an early publisher&rsquo;s uninformed sequencing) as symphonies 83, 85 and 87 in 1785; Nos. 82, 84 and 86 followed over the next year. First performed to great acclaim during the Loge Olympique&rsquo;s 1787 concert season, they have been known ever since as his &lsquo;Paris&rsquo; symphonies. Haydn never set foot in Paris, by the way; he simply dispatched the symphonies there for performance.</p>
				<p>The Loge&rsquo;s orchestra was the largest in Europe, far bigger than the Esterházy court ensemble with which Haydn was accustomed to working. It sported 40 violins, 10 double basses and matching ranks of virtuoso wind players (more players in fact than many full modern orchestras!). The musicians decked themselves out with chic to match their reputation. They performed wearing dashing sky-blue dress coats, swords swinging from their waist-bands.</p>
				<p>Symphony No. 82 opens with a bold, vigorous theme. Haydn contrasts it with a second strain characterized by an exquisite sense of nonchalance, and containing what sounds virtually like a sigh. The slow movement bears the unusually quick tempo marking Allegretto. It is a set of variations, a form which Haydn used with great regularity and, as here, with satisfying, wide-ranging ingenuity.</p>
				<p>He deftly contrasts the courtly formality of the third movement minuet&rsquo;s outer panels with a more loose-limbed central trio. The jovial finale is the source of the symphony&rsquo;s nickname. Its bagpipe-like drone bass and rustic principal theme reminded early listeners of the dancing bears which were a common feature at country fairs of the day.</p>
				<p>Throughout his lengthy, industrious career, Haydn&rsquo;s essential optimism never deserted him. Late in life, he wrote, &ldquo;Often when contending with obstacles of every sort that interfered with my work, often when my powers of both body and mind were failing and I felt it a hard matter to persevere on the course I had entered on, a secret feeling within me whispered, &lsquo;There are but few contented and happy men here below; grief and care prevail everywhere; perhaps your labours may one day be the source from which the weary and worn, or the man burdened with affairs, may derive a few moments&rsquo; rest and refreshment.&rsquo; What a powerful motive for pressing onward!&rdquo;</p>
			</div>
			<div class="tab-pane fade" id="extras">
					<p><strong><a href="http://www.haleyrempel.com/">Haley Rempel</a>, two-minute talk<br />Number 31: &lsquo;The Trouble with Mozart&rsquo;</strong></p>
					<section class="row">
  					<div class="span5">
  						<div class="flex-video widescreen">
  							<iframe width="500" height="281" src="http://www.youtube.com/embed/a-zDQvSs9qE" frameborder="0" allowfullscreen seamless></iframe>
  							<p class="fineprintdark">Praised for her warm tone and expressive playing, Canadian flutist <strong><a href="http://www.haleyrempel.com/">Haley Rempel</a></strong> is gaining reputation for her sophisticated interpretations as well as her unique ability to capture audiences. Haley facilitates the MCO's Pizza Club events.</p>
  							<p>&nbsp;</p>
  						</div>
  					</div>
  				</section>
				<p><strong><a href="http://www.haleyrempel.com/">Haley Rempel</a>, two-minute talk<br />Number 28: &lsquo;On Franz Joseph Haydn&rsquo;</strong></p>
					<section class="row">
  					<div class="span5">
  						<div class="flex-video widescreen">
  							<iframe width="510" height="287" src="http://www.youtube.com/embed/gYytiyYbPws" frameborder="0" allowfullscreen seamless></iframe>
  							<p>&nbsp;</p>
  						</div>
  					</div>
					</section>
					<section class="row">
						<div class="span5">
							<h4>Review:<br />Light &amp; bright</h4>
							<p class="fineprintdark"><a href="http://www.winnipegfreepress.com/">Winnipeg Free Press</a>, by Gwenda Nemerofsky<br />Manitoba Chamber Orchestra; Anne Manson, conductor; Janina Fialkowska, piano<br />Westminster United Church; Tue, Feb 19<br />Attendance: 672<br />Four stars out of five<br>&nbsp;</p>
							<p>She&rsquo;s given performances the world over with the most famous orchestras, she&rsquo;s recorded more than 15 CDs and she recently received the Governor General&rsquo;s Performing Arts Award for lifetime achievement in classical music. But when renowned Montreal-born pianist Janina Fialkowska takes the stage, there is an honest demureness that endears her to her audience.</p>
							<p>On Feb. 19, she performed Mozart&rsquo;s Piano Concerto No. 12 in A major, K414 with the Manitoba Chamber Orchestra under the baton of Anne Manson.</p>
							<p>This is a lovely, lyrical concerto and Fialkowska introduced the opening melody with a refreshingly natural simplicity, well enunciated, with limpid ornaments. She made phrases sing and burble with uplifting joyfulness. Her fingers seemed to barely alight on the keys, as she maintained a light brightness throughout the Allegro.</p>
							<p>Fialkowska approached the stately beginning of the Andante with thoughtful patience. Ideas rolled out clearly in her distinct, deliberate style &mdash; not overdone, which is true to the score. Echoes of the Allegro wove in and out.</p>
							<p>The Allegretto was gently playful and understated. Fialkowska&rsquo;s pure artistry made it all seem so easy. She brought Mozart&rsquo;s voice to our ears through the magic of her hands. The audience provided rousing applause, persuading Fialkowska to play a stunning Chopin ringer as an encore.</p>
							<p>Gary Kulesha&rsquo;s 1985 <i>Serenade for String Orchestra</i>, written for the MCO, marked a departure from his usual atonal compositional style. Four movements long, it opened with dense, intense harmonies, then mellowed into pleasing tunefulness, rich with assertive cello and bass lines. The Scherzo was spirited, syncopated and dance-like and the Romance was true to its name, albeit a bittersweet take. Smooth, long phrases were highlights, while the high-pitched insect-like violin section was a little hard on the ears. Manson imbued a sense of power and authority to the majestic Finale.</p>
							<p>The evening began with the charming <i>Born by the River</i> by Winnipeg-born composer, cellist and university professor Karen Sunabacka. She introduced the piece, explaining the influence and inspiration she gained from her M&eacute;tis grandmother. Strains of the fiddle tune <i>The Old French</i> were evident immediately, as the work captured its liveliness and humour. Use of momentary silences and pizzicato grabbed our attention.</p>
							<p>The night wrapped up with an energetic reading of Haydn&rsquo;s Symphony No. 82 in C Major &mdash; &lsquo;The Bear.&rsquo; After a brief audience lesson from Manson in the construction of the first movement, the MCO, bolstered by woodwinds and timpani, launched into the Vivace with plenty of oomph. The French horns had a few difficulties with their upper notes and the Menuetto and Trio was a bit heavy-handed, but you couldn&rsquo;t help but warm to the sprightly finale with its unmistakable bagpipe-like drone in the cellos and basses. A great effort all-round.</p>
						</div><!-- /span5 -->
					</section>
					<section class="row">
						<div class="span5">
							<h4>Critique:<br>Janina Fialkowska au Manitoba Chamber Orchestra<br>de la tr&egrave;s belle musique</h4>
							<p class="fineprintdark">Publi&eacute; par <a href="http://la-liberte.mb.ca/"><i>La Libert&eacute;</i></a>, le 27 f&eacute;vrier 2013<br>&nbsp;</p>

							<p>Les amateurs de Mozart et de piano ont &eacute;t&eacute; choy&eacute;s par la venue &agrave; Winnipeg de la r&eacute;put&eacute;e pianiste Janina Fialkowska le 19 f&eacute;vrier pour jouer le 12e concerto pour piano de Mozart avec le Manitoba Chamber Orchestra et donner un r&eacute;cital le lendemain au b&eacute;n&eacute;fice du MCO, quelques jours apr&egrave;s le passage de madame Angela Cheng &agrave; l&rsquo;Orchestre symphonique de Winnipeg pour le 25e concerto pour piano de Mozart, que j&rsquo;ai comment&eacute; dans ma derni&egrave;re chronique.</p>
							<p>Au d&eacute;but des ann&eacute;es 1780, Mozart connaissait le succ&egrave;s et &eacute;tait surtout reconnu comme un pianiste virtuose. Il venait de s&rsquo;installer &agrave; Vienne et avait mari&eacute; Constanze Weber le 4 ao&ucirc;t 1782. Il organisait des s&eacute;ries de concerts par abonnement, pour lesquelles il a compos&eacute; de nombreuses oeuvres, dont trois concertos pour la s&eacute;rie du d&eacute;but de 1783, les 11, 12 et 13. Cette s&eacute;rie fut annul&eacute;e apr&egrave;s le premier concert faute d&rsquo;un nombre suffisant d&rsquo;abonn&eacute;s. C&rsquo;est probablement lors de ce concert que fut cr&eacute;&eacute; le concerto no 12.</p>
							<p>Je mentionnais, &agrave; propos du 25e concerto, que c&rsquo;est dans les p&eacute;riodes les plus difficiles de sa vie que Mozart a &eacute;t&eacute; inspir&eacute; de ses plus belles oeuvres. Ce qui ne signifie pas que celles qu&rsquo;il a compos&eacute;es dans les moments heureux de sa vie, comme les concertos 11, 12 et 13, ne soient pas aussi de petits chefs-d&rsquo;oeuvre dont la beaut&eacute; et la fra&icirc;cheur ne cessent de s&eacute;duire les auditoires depuis plus de deux si&egrave;cles. Dans une lettre &agrave; son p&egrave;re, Mozart a d&eacute;crit les trois concertos comme &ldquo;un heureux &eacute;quilibre entre le trop facile et le trop difficile; ils sont tr&egrave;s brillants, agr&eacute;ables &agrave; l&rsquo;oreille et naturels, sans &ecirc;tre insipides. Il y a des passages ici et l&agrave; que seuls les connaisseurs pourront vraiment appr&eacute;cier; mais ces passages sont &eacute;crits de façon &agrave; plaire tout autant aux moins avertis, sans qu&rsquo;ils sachent pourquoi.&rdquo;</p>
							<p>Si le 12e concerto n&rsquo;a pas &eacute;t&eacute; &eacute;crit pour &eacute;pater par des prouesses techniques, il n&rsquo;en demande pas moins de la virtuosit&eacute; et surtout une grande sensibilit&eacute; pour en exprimer toutes les subtilit&eacute;s et le rendre int&eacute;ressant. En parfaite complicit&eacute; avec Anne Manson &agrave; la direction de l&rsquo;orchestre, madame Fialkowska en a donn&eacute; une interpr&eacute;tation brillante, divertissante et pleine de finesse. Comme Angela Cheng, Janina Fialkowska est une artiste accomplie qui peut jouer avec un certain d&eacute;tachement des contraintes mat&eacute;rielles et techniques, pour atteindre un niveau d&rsquo;expression purement musicale. Ce fut un r&eacute;gal d&rsquo;entendre cette musique dans l&rsquo;enceinte de la Westminster United Church, dont les dimensions et l&rsquo;acoustique ressemblent beaucoup aux salles europ&eacute;ennes o&ugrave; elle &eacute;tait jou&eacute;e par Mozart. On y retrouve une ambiance intime qui rehausse grandement la qualit&eacute; de l&rsquo;&eacute;coute, une qualit&eacute; d&rsquo;&eacute;coute qui inspire les musiciens qui se sentent davantage en &ldquo;communion&rdquo; avec l&rsquo;auditoire. En rappel, Mme Fialkowska a brillamment interpr&eacute;t&eacute; la Valse en mi mineur op. posthume de Chopin.</p>
							<p><b>Janina Fialkowska</b></p>
							<p>Comme elle en a l&rsquo;habitude, Anne Manson avait compos&eacute; un programme bien structur&eacute; dans lequel la musique contemporaine s&rsquo;est int&eacute;gr&eacute;e harmonieusement &agrave; la musique du 18e si&egrave;cle. Il a d&eacute;but&eacute; par la cr&eacute;ation d&rsquo;une oeuvre command&eacute;e &agrave; la compositrice manitobaine Karen Sunabacka, par le Conseil des arts du Manitoba intitul&eacute;e <i>Born by the River</i>. C&rsquo;est une oeuvre dans laquelle elle &eacute;voque l&rsquo;h&eacute;ritage de sa grand-m&egrave;re maternelle m&eacute;tisse. De style classique, la pi&egrave;ce est une suite de petits tableaux tr&egrave;s color&eacute;s et vivants. Sous la direction inspir&eacute;e d&rsquo;Anne Manson, l&rsquo;orchestre en a donn&eacute; une belle ex&eacute;cution, qui pr&eacute;parait bien &agrave; l&rsquo;audition du concerto de Mozart.</p>
							<p>La deuxi&egrave;me partie a commenc&eacute; par une oeuvre de Gary Kulesha que le MCO avait cr&eacute;&eacute;e en 1985, qu&rsquo;il a remani&eacute;e par la suite. S&eacute;r&eacute;nade pour orchestre &agrave; cordes est une oeuvre dans laquelle Kulesha renoue avec le style de la musique classique de r&eacute;pertoire qu&rsquo;il affectionnait dans sa jeunesse tout en se permettant quelques touches de modernit&eacute;. C&rsquo;est une musique agr&eacute;able &agrave; entendre. A suivi la Symphonie no 2 de Hayden dite l&rsquo;Ours. Anne Manson a infus&eacute; beaucoup d&rsquo;esprit &agrave; cette petite symphonie vivante et divertissante. On l&rsquo;a surnomm&eacute;e l&rsquo;Ours &agrave; cause d&rsquo;un emprunt &agrave; la musique sur laquelle les dompteurs qui faisaient danser des ours lors des f&ecirc;tes foraines.</p>
							<p>Le lendemain, c&rsquo;est dans l&rsquo;ambiance encore plus intime du salon Provencher de l&rsquo;H&ocirc;tel Fort Garry que Janina Fialkowska a donn&eacute; un r&eacute;cital d&rsquo;oeuvres de Schubert et Chopin au b&eacute;n&eacute;fice du MCO. Madame Fialkowska a avou&eacute; qu&rsquo;elle avait longtemps h&eacute;sit&eacute; &agrave; ajouter Schubert, qu&rsquo;elle admire pourtant, &agrave; son r&eacute;pertoire. Inventeur du lied, un po&egrave;me chant&eacute;, Schubert a apport&eacute; une dimension lyrique nouvelle &agrave; la musique et a influenc&eacute; de nombreux compositeurs par la suite. Elle a expliqu&eacute; que les oeuvres de Schubert ressemblent &agrave; de longues promenades paisibles et romantiques dans la campagne, pendant lesquelles notre pens&eacute;e n&rsquo;est distraite que par la beaut&eacute; et le parfum d&rsquo;une fleur, par le chant d&rsquo;un oiseau ou le murmure d&rsquo;un ruisseau. &ldquo;On ne sera pas arrêt&eacute; par les chutes Niagara ou le Grand Canyon pendant ces promenades&rdquo; disait-elle avec humour en pr&eacute;sentant les pi&egrave;ces qu&rsquo;elle a jou&eacute;es. Pour que ces pi&egrave;ces tr&egrave;s lyriques aux nombreuses r&eacute;p&eacute;titions ne deviennent pas ennuyeuses, il faut avoir d&eacute;velopp&eacute; un sens musical et une maturit&eacute; artistique qui permettent de sortir de la banalit&eacute; apparente pour amener l&rsquo;auditeur dans un &eacute;tat m&eacute;ditatif et d&rsquo;&eacute;merveillement. Son interpr&eacute;tation des Quatre impromptus a &eacute;t&eacute; sublime, empreinte d&rsquo;&eacute;motion et de d&eacute;licatesse. Comme elle le souhaitait, elle a entraîn&eacute; l&rsquo;auditoire dans un univers enchant&eacute;.</p>
							<p>Madame Fialkowska a une longue &ldquo;relation d&rsquo;amour&rdquo; avec Chopin, dont elle est consid&eacute;r&eacute;e comme l&rsquo;une des meilleures interpr&egrave;tes de notre temps. Dans un entretien avec Bill Richardson, de la CBC, avant de retourner au piano, elle a expliqu&eacute; que son rapport avec la musique de Chopin a beaucoup &eacute;volu&eacute; avec le temps. Chopin a aussi &eacute;t&eacute; un grand innovateur en son temps, faisant progresser la technique pianistique par les nombreuses Études qu&rsquo;il a compos&eacute;es. Au d&eacute;but, jouer Chopin repr&eacute;sentait un d&eacute;fi technique auquel elle s&rsquo;attaquait avec toute la fougue de sa jeunesse. Aujourd&rsquo;hui, le d&eacute;fi consiste plut&ocirc;t &agrave; se laisser emporter par la musique jusqu&rsquo;&agrave; se sentir presque en symbiose avec le compositeur, sans perdre le contr&ocirc;le de l&rsquo;ex&eacute;cution, &agrave; se d&eacute;tacher du clavier pour atteindre un niveau spirituel tout en ayant conscience de ce qui se passe au clavier. Elle a interpr&eacute;t&eacute; de façon &eacute;blouissante le Scherzo no 4, la Valse en la b&eacute;mol majeur et le Scherzo no 1. Elle a jou&eacute; ces pi&egrave;ces tr&egrave;s techniques avec une belle musicalit&eacute; et une &eacute;l&eacute;vation qui nous a entraîn&eacute;s au-del&agrave; de la mat&eacute;rialit&eacute; du piano.</p>
							<p>On se souviendra longtemps de cette belle soir&eacute;e pass&eacute;e en compagnie de madame Fialkowska, une artiste exceptionnelle qui nous a touch&eacute;s par sa grande simplicit&eacute;, son naturel et sa grande g&eacute;n&eacute;rosit&eacute;.</p>
						</div><!-- /span5 -->
					</section>

				</div>
			</div><!-- /tab-content -->

		</div><!-- /tab content well -->

	</div><!-- /span6 tab area -->

</div><!-- /row -->

<?php get_template_part('templates/content', 'concert'); ?>

</div><!-- /container -->
