<?php
/*
Template Name: Page Concert7 Template
*/
?>
<div class="container">

<div class="row">

	<div class="span8">
		<img src="http://www.themco.ca/wp-content/uploads/2013/01/head02apr13.jpg" alt="" width="770" height="455">
	</div>
	<div class="span2">
		<p>.</p>
	</div>

</div><!-- /row -->

<div class="row">

	<div class="span7">
		<h4>Time machine:<br />hear the first MCO concert ever!</h4>
		<p>After just one concert, Winnipeggers knew that we needed to have live chamber music performed in this town for at least the next forty years.</p>
		<p>Anne Manson: &ldquo;This concert will be an almost exact replica of the first concert MCO ever played, forty years ago. We are so happy to have Tracy Dahl back with us for Britten&rsquo;s <em>Les Illuminations</em>. And the audience will have a chance to get to know Caitlin Broms-Jacobs featured in a Vivaldi oboe concerto.&rdquo;</p>
		<p>Roy Goodman, who occupies his own volume in the tome of MCO&rsquo;s history (as Music Director from 2000 to 2005), will once again be at the podium for this happy occasion.</p>
		<p><strong>Maestro Roy Goodman</strong></p>
		<p>Roy Goodman is Principal Guest Conductor of the English Chamber Orchestra, Director Emeritus of the European Union Baroque Orchestra, Honorary President of the Royal Scottish National Orchestra Chorus and has appeared as guest conductor with 120 other orchestras and opera houses.</p>

		<div>
			<p>
  			<img src="http://www.themco.ca/wp-content/uploads/2013/01/PreConcert.png"><button id="preconcert" class="btn btn-small btn-inverse" rel="popover" data-placement="top" data-original-title="Pre-concert event" data-content="Arrive early for more music! Hear a special presentation by the Beautiful Saviour Lutheran School strings group; 6:45 pm.">Event</button> <button id="pizza" class="btn btn-small btn-inverse" rel="popover" data-placement="top" data-original-title="Pizza Club" data-content="Book three days in advance for MCO&rsquo;s Pizza Club! Arrive at 6 pm for pizza and a pre-concert presentation, followed by the concert. Tickets are $7.50 for students, including pizza; adults pay regular price. Space is limited; call 204.783.7377 to reserve yours.">Pizza Club</button> <button id="mcnally" class="btn btn-small btn-inverse" rel="popover" data-placement="top" data-original-title="McNally Robinson event" data-content="On Monday, April 1st, hear a special presentation with conductor Roy Goodman and oboist Caitlin Broms-Jacobs; McNally Robinson, Grant Park Shopping Centre.">McNally Robinson</button>
			</p>
		</div>

		<strong>The concert begins at 7:30 pm on April 2nd in <a href="http://www.westminsterchurchwinnipeg.ca">Westminster United Church</a>, 745 Westminster at Maryland. Tickets are $26.50 for adults, $24.50 for seniors and $7.50 for students, including GST, at <a href="http://www.mcnallyrobinson.com/home" title="McNally Robinson">McNally Robinson</a>, the <a href="http://www.wecc.ca/" title="West End Cultural Centre">West End Cultural Centre</a> (586 Ellice at Sherbrook), <a href="http://www.organicplanet.coop/" title="Organic Planet">Organic Planet</a> (877 Westminster Ave) or MCO's Ticketline (783-7377).</strong>
		<p class="fineprint">&nbsp;<p>
	</div><!-- /span7 -->

	<div class="span1"> 
		<img src="http://retmco-shungite.rhcloud.com/wp-content/uploads/2012/10/BuyTicketsHereHi.png" alt="" width="75" height="150" /><br />
	  <a href="http://www.1shoppingcart.com/SecureCart/SecureCart.aspx?mid=292CFDD8-2004-4B27-8455-B26B8A4D841F&pid=98a53d33021f46ffb6ceca8382c830cd"><img rel="tooltip" title="Click to add adult ticket to cart" data-placement="left" src="http://www.themco.ca/wp-content/uploads/2013/01/AdultC.png" alt="" width="62" height="40" /></a><br />
 	  <a href="http://www.1shoppingcart.com/SecureCart/SecureCart.aspx?mid=292CFDD8-2004-4B27-8455-B26B8A4D841F&pid=572a100f29294416b420bdcaf1bd918a"><img rel="tooltip" title="Click to add senior ticket to cart" data-placement="left" src="http://www.themco.ca/wp-content/uploads/2013/01/SeniorC.png" alt="" width="62" height="40" /></a><br />
	  <a href="http://www.1shoppingcart.com/SecureCart/SecureCart.aspx?mid=292CFDD8-2004-4B27-8455-B26B8A4D841F&pid=3a96d1afe5434b8cb4787766f9dbb1dc"><img rel="tooltip" title="Click to add student ticket to cart" data-placement="left" src="http://www.themco.ca/wp-content/uploads/2013/01/StudentC.png" alt="" width="62" height="40" /></a>
		<p class="fineprint">Click ticket above to add to shopping cart; adjust quantity in cart and return to purchase other types of tickets.</p>
	</div><!-- /span2 -->

</div><!-- /row -->

<div class="row">

	<div class="span6">

		<div class="well"><!-- tab content well -->

		<ul class="nav nav-pills">
			<li class="active"><a href="#repertoire" data-toggle="tab"><strong>Repertoire</strong></a></li>
			<li><a href="#bios" data-toggle="tab"><strong>Artists</strong></a></li>
			<li><a href="#notes" data-toggle="tab"><strong>Notes</strong></a></li>
		</ul>
		<div class="tab-content">
			<div class="tab-pane fade in active" id="repertoire">
				<p><strong>Manitoba Chamber Orchestra</strong><br />Anne Manson, Music Director<br />Karl Stobbe, Concertmaster<br />Westminster United Church<br />2 April 2013</p>
				<p>Roy Goodman, conductor<br />Tracy Dahl, soprano<br />Caitlin Broms-Jacobs, oboe</p>
				<p><strong>Edvard Grieg</strong><br /><em>From Holberg’s Time</em> (Suite in olden style), Op. 40</p>
				<p><strong>Benjamin Britten</strong><br /><em>Les Illuminations</em>, Op. 18</p>
				<p><strong>Antonio Vivaldi</strong><br />Concerto in A Minor, for Oboe, Strings<br />and Harpsichord, RV 463 (F VII-13)</p>
				<p><strong>John Estacio</strong><br /><em>Such Sweet Sorrow</em></p>
				<p><strong>Gioachino Rossini</strong><br />Sonata No. 3, for Strings in C Major</p>
				<p>Concert sponsor / <strong>Angela &amp; Robert Ross</strong><br />Season sponsor / <strong><a href="http://www.greatwestlife.com/001/Home/index.htm">The Great-West Life Assurance Company</a></strong><br />Print media sponsor / <strong><a href="http://www.winnipegfreepress.com/">Winnipeg Free Press</a></strong><br />Radio media sponsors / <strong><a href="http://music.cbc.ca/#/radio2/">CBC Radio 2 98.3</a></strong>, <strong><a href="http://www.cbc.ca/programguide/daily/today/cbc_radio_one">CBC Radio One 990</a></strong>,<br /><strong><a href="http://www.espace.mu/Espace-Musique/">Espace musique 89,9</a></strong> and <strong><a href="http://www.goldenwestradio.com/">Golden West Radio</a></strong>
			</div>
			<div class="tab-pane fade" id="bios">
				<p><strong>Roy Goodman</strong></p>
				<p>Roy Goodman is Principal Guest Conductor of the English Chamber Orchestra. He has worked as guest conductor with over 120 orchestras and opera companies worldwide &mdash; from Carnegie Hall to the Royal Albert Hall Proms in London; from Berlin Philharmonic Hall to the Sydney Opera House. In 2011 Radio New Zealand affectionately named him the &lsquo;Rafa Nadal&rsquo; of conductors!</p>
				<p>Goodman is well known for his work as director and founder of the Brandenburg Consort (1975-2001), as co-director / founder of The Parley of Instruments (1978-1986), co-founder of the London Handel Orchestra (in 1981), Principal Conductor of the Hanover Band (1986-1994), Music Director of the European Union Baroque Orchestra (1989-2004), Principal Conductor of the Händel Festspiele at the Badisches Staatstheater in Karlsruhe (1990-1998), the first Principal Conductor of Ume&aring; Symphony Orchestra and Northern Opera Sweden (1995-2001), Conductor of the V&auml;ster&aring;s Sinfonietta in Sweden (1995-2011), Music Director of the Manitoba Chamber Orchestra (1999-2005), the first Principal Conductor of Holland Symfonia and Dutch National Ballet (2003-2006), Conductor of the Bachkoor Holland accompanied by the Amsterdam Royal Concertgebouw Kamerorkest (2003-2010), and Principal Guest Conductor of the Auckland Philharmonia in New Zealand (2007-2011).</p>
				<p>Born in January 1951, Roy Goodman achieved international fame with King&rsquo;s College Choir as the boy soloist in Allegri&rsquo;s <em>Miserere</em> (Decca 1963). Already in 1970 he became a Fellow of the Royal College of Organists, and he completed his studies with a violin performer&rsquo;s ARCM and a music teacher&rsquo;s diploma. In 1979 Goodman was a founder member of Ton Koopman&rsquo;s Amsterdam Baroque Orchestra, then he joined Trevor Pinnock&rsquo;s English Concert, and in 1987 became the first Concertmaster of the Orchestra of the Age of Enlightenment (collaborating with Sir Charles Mackerras, Sir Simon Rattle, Frans Brüggen and Ivan Fischer). Also during the 1980s he directed for CD with the Hanover Band the first ever performances on historic instruments of the complete symphonies by Beethoven, Schubert, Schumann and Weber, as well as 14 symphonies by Mendelssohn and 60 symphonies by Haydn. He has directed over 120 CDs ranging from Monteverdi&rsquo;s sacred vocal music to Holst&rsquo;s Planets, in addition to conducting more than forty world premieres of contemporary music.</p>
				<p>Guest appearances in recent years have included Stuttgart and San Francisco Operas, the four German Radio Symphony orchestras, the Amsterdam Royal Concertgebouw, BBC Philharmonic, Royal Liverpool Philharmonic and Hallé Orchestras. During 2011/12 Goodman also conducted the Royal Scottish National Orchestra, the Orchestra of the Age of Enlightenment, Melbourne Symphony Orchestra and the West Australian Symphony Orchestra in Perth. He made his debut at the Sydney Opera House with three concerts in April 2010.</p>
				<p>Roy Goodman is an honorary Doctor of Music (University of Hull) and in 2005 was made an honorary Fellow of the Royal College of Music. He has three children and four grandchildren, and he loves downhill skiing, squash and offshore sailing &mdash; in Summer 2010 he completed a 2,800 mile solo circumnavigation of the UK and Ireland (see blog page!).</p>
				<p><strong>Tracy Dahl</strong></p>
				<p>With her 2006 debut at La Scala as Zerbinetta in <em>Ariadne auf Naxos</em>, Canada&rsquo;s premier coloratura soprano, Tracy Dahl, achieved another milestone in a career that has taken her to the Metropolitan Opera, the San Francisco Opera, the Houston Grand Opera, the Santa Fe Opera, the Canadian Opera Company, and the Châtelet in Paris, to name but a few. Her &ldquo;superlative coloratura&rdquo; (Globe and Mail), is regularly singled out by critics. &ldquo;Her extreme high notes, and she threw in a lot of them, are easy and spectacular&rdquo; (Boston Globe). She has &ldquo;a voice filled with sunshine, rainbows and laser light&rdquo; according to Opera Magazine and the San Francisco Chronicle finds her &ldquo;bright, sparkling, and bouncing, accurate and winning.&rdquo; &ldquo;Where pure, well-tuned, characterful, and seemingly easy acrobatics through two and a half octaves are required, Dahl is among a relative few who can do it all superlatively well,&rdquo; comments the Calgary Herald. In 2009 she was awarded the Opera Canada Award.</p>
				<p>Highlights of 2012 included two trips to Australia with the Melbourne and Sydney symphonies, works by Bach and Mozart with the Vancouver Symphony, and the title role of Maria Stuarda with the Pacific Opera Victoria. During the summer she returned to the Opera Theatre of St. Louis for Unsuk Chin&rsquo;s opera <em>Alice in Wonderland</em> in the role of the Cheshire Cat and sang Gershwin songs with the New York Philharmonic under Bramwell Tovey.</p>
				<p>In season 2010 Dahl portrayed the quirky Violet Beauregard in the world premiere of <em>The Golden Ticket</em> at the Opera Theatre of St. Louis and appeared with the Vancouver Symphony.</p>
				<p>Among her many notable debuts at major opera houses have been as Adele in <em>Die Fledermaus</em> at the Metropolitan Opera (later returning as Zerbinetta and as Florestine in the world premiere and revival productions of <em>The Ghosts of Versailles</em>), as Olympia in the San Francisco Opera production of <em>Les Contes d&rsquo;Hoffmann</em> opposite Plácido Domingo (where she returned as Oscar in <em>Un Ballo in Maschera</em> and Lucia in <em>Lucia di Lammermoor</em>), Amor in the Los Angeles Music Center Opera staging of <em>Orpheus in the Underworld</em>. She was also heard as Despina in <em>Cosí Fan Tutte</em> with the Dallas Opera; and Eurydice in <em>Orpheus in the Underworld</em> with Michigan Opera Theater and Houston Grand Opera, where she also sang Oscar. Dahl was Gretel in <em>Hansel and Gretel</em> with the Cleveland Opera. She appeared as Servilia in New York City Opera&rsquo;s production of <em>La Clemenza di Tito</em>.</p>
				<p>Dahl has performed with every major Canadian orchestra. Other orchestral engagements have included a New Year&rsquo;s Eve Gala concert with the Philadelphia Orchestra under David Zinman and appearances with the Atlanta Symphony Orchestra during the Atlanta &lsquo;96 Olympics Arts Festival. Dahl performed with the American Symphony Orchestra in the world premiere of David Del Tredici&rsquo;s <em>Child Alice</em> at Carnegie Hall. She appeared with the San Francisco Symphony in Handel&rsquo;s <em>Messiah</em>, and with the Saint Louis Symphony under Leonard Slatkin. She also performed with maestro Slatkin at the Hollywood Bowl, joined the Tonhalle Orchestra/Zurich under Zinman for a gala New Year&rsquo;s Eve concert, and made her United Kingdom debut with the Royal Scottish National Orchestra.</p>
				<p>Her discography includes <em>A Disney Spectacular</em> with the Cincinnati Pops (Telarc), <em>Glitter and Be Gay</em> with the Calgary Philharmonic (CBC), <em>A Gilbert and Sullivan Gala</em> with the Winnipeg Symphony Orchestra (CBC), and <em>Love Walked In</em>, a Gershwin collection with the Bramwell Tovey Trio (Red Phone Box Company).</p>
				<p><strong>Caitlin Broms-Jacobs</strong></p>
				<p>Described as &ldquo;a delightfully musical player, with elegant tone and delivery&rdquo; (Winnipeg Free Press), Caitlin Broms-Jacobs is now in her fourth season as principal oboist of the Manitoba Chamber Orchestra. Caitlin enjoys a wide-ranging career of chamber music, recital, orchestral, and solo performances, and performs frequently in Winnipeg and across Canada.  Caitlin has served as guest principal oboist of the Winnipeg Symphony Orchestra and was formerly principal oboist of the Saskatoon Symphony Orchestra. She has performed with the Toronto Symphony Orchestra, the New World Symphony, the National Ballet Orchestra, and the Pacific Music Festival Orchestra.  Caitlin has, as principal oboist, performed with numerous conductors including Simon Streatfeild, Nello Santi, Yakov Kreizberg, Jun Markl, and Valery Gergiev.</p>
				<p>Caitlin frequently collaborates with composers and performs contemporary music. She has been featured in Winnipeg&rsquo;s GroundSwell series and can be heard broadcast on CBC Radio 2. She enjoys studio recording and has most recently recorded with renowned bass-baritone Victor Engbrecht.</p>
				<p>A native of Toronto, Caitlin studied with Keith Atkinson at the Royal Conservatory of Music&rsquo;s Young Artists Performance Academy. She received her Bachelor of Music degree from the Eastman School of Music where she studied with Richard Killmer. She continued her studies with Chicago Symphony Orchestra principal oboist Eugene Izotov.</p>
				<p><strong>John Estacio</strong></p>
				<p>One of Canada&rsquo;s most frequently performed and broadcast composers, John Estacio has served as Composer-in-Residence for the Edmonton Symphony Orchestra, the Calgary Philharmonic Orchestra, and the Calgary Opera. These residencies yielded several works, many of which can be found on the CD entitled <em>Frenergy, the Music of John Estacio</em>. This CD earned Estacio two JUNO nominations and a Western Canadian Music Award. His frequent performances and broadcasts have earned him several SOCAN Concert Music Awards.</p>
				<p>Estacio is the recent recipient of the National Arts Centre Award for Composers, which will result in three commissioned works for the National Arts Centre Orchestra. His most recent opera, <em>Lillian Alling</em>, premiered in Vancouver in 2010. His first opera, <em>Filumena</em>, has been remounted five times, and was filmed for television.</p>
				<p>In the 2010/11 season, the Toronto Symphony Orchestra gave the Carnegie Hall premiere of <em>Frenergy</em>. The Royal Winnipeg Ballet featured several of Estacio&rsquo;s orchestral works in a new ballet, <em>Wonderland</em>, with choreography by Shawn Hounsell.</p>
				<p>Estacio recently completed a cantata for chorus and orchestra, and a Sinfonietta for the Victoria Symphony. He has also written for the symphony orchestras of Toronto, Montréal and Vancouver, and the Manitoba Chamber Orchestra. His works have been performed by the Houston Symphony, Rochester Philharmonic Orchestra, Fort Wayne Philharmonic, and the Manila Symphony, and his choral work Eulogies has entered the repertoire of several choirs. His arrangements of seven songs by Jean Sibelius were performed by Ben Heppner and the Los Angeles Philharmonic in London and Paris.</p>
				<p>The Canadian Broadcasting Corporation commissioned <em>Such Sweet Sorrow</em> for the Manitoba Chamber Orchestra. The premiere performance was given 7 February 2001 by conductor Roy Goodman and the MCO.</p>
			</div>
			<div class="tab-pane fade" id="notes">
				<p><strong>From Holberg&rsquo;s Time<br />(Suite in Olden Style), Op. 40<br />Edvard Grieg</strong></p>
				<p>The year 1884 marked the two hundredth anniversary of Ludvig Holberg, an important Norwegian scholar and author. His immensely popular, satirical stage comedies earned him the nickname &lsquo;The Molière of the North.&rsquo; Grieg received a commission to celebrate the occasion with a cantata for unaccompanied male chorus, and a piano suite that re-imagined the dance forms of Holberg&rsquo;s era. Hence the suite&rsquo;s full title: <em>From Holberg&rsquo;s Time &mdash; Suite in Olden Style</em>. Other composers have paid similar tributes to previous eras. Tchaikovsky had written his Variations on a Rococo Theme for Cello and Orchestra, for example, during the previous decade.</p>
				<p>Grieg stated that his aim with the suite was to &ldquo;resurrect for a brief instant, times of long ago.&rdquo; His primary models were the harpsichord works of French composers such as Rameau and Couperin. He may also have had in mind three other, non-French masters who were born the year after Holberg: Bach, Handel and Scarlatti. In the suite, he used several types of pieces that all these composers employed regularly, including sarabande and gavotte.</p>
				<p>Grieg gave the first performance himself, on the exact anniversary of Holberg&rsquo;s birth. The cantata was premiered that day as well, in the marketplace at Bergen during the unveiling of a statue of Holberg. Grieg transcribed the suite for string orchestra the following year, and this is the form in which it is most often heard.</p>
				<p>It is music of great beauty, warmth, and variety. Homage to Baroque style it may be, but Grieg&rsquo;s folk-flavoured Romantic idiom is heard clearly, too. Much of the suite&rsquo;s appeal lies in his skilful use of the strings, either for delicate effects or massed sonorities. The perpetual motion-style Prelude deftly mixes the exuberant and the wistful. The following Sarabande has a grave, simple beauty. You may recognize the gracious third movement, Gavotte and Musette. For many years it was the opening theme of CBC Radio Two&rsquo;s classical request program, RSVP. The suite reaches its emotional summit in the fourth section, a beautiful, gravely expressive Air. Grieg here produced greater depth of feeling than would have been common during Holberg&rsquo;s era, but total authenticity was not his primary consideration. A lively and jovial Rigaudon, sporting brief solos for violin and viola, and a melancholy, minor-key central section, concludes the suite.</p>
				<p><strong>Les Illuminations, Op. 18<br />Benjamin Britten (Lord Britten of Aldeburgh)</strong></p>
				<p><em>&ldquo;For that, as I see it is our job.<br />To be useful to the living.&rdquo;<br />&mdash; Benjamin Britten</em></p>
				<p>Britten made himself &ldquo;useful&rdquo; (a typically modest description) in many ways. Other composers have possessed the industry to work in as wide a range of creation as he. However, he numbered among the rare, precious few who have also been blessed with the talent, imagination and sensitivity to write outstanding compositions in each genre.</p>
				<p>He adopted an abundantly communicative style, fundamentally conservative but regularly sparked by adventurousness. Within it, he composed everything from opera, oratorio, orchestral and chamber works, to film scores, folk song arrangements and music aimed without condescension at children.</p>
				<p>Few have matched the depth and balance of his insight into both the dark and the light sides of human nature. For every profound drama that flowed from his pen &mdash; the orchestral work <em>Sinfonia da Requiem</em>, for example &mdash; he created a witty counterweight such as the Diversions for Piano Left Hand and Orchestra. Add to these his formidable abilities as pianist, scholar, administrator and conductor (of other composers&rsquo; music in addition to his own), and you have a figure for the ages. The MCO is honoured to pay tribute to him in the centenary year of his birth.</p>
				<p>Britten&rsquo;s love affair with words began early and endured throughout his life. In 1938, a friend, the celebrated poet W.H. Auden, introduced him to the works of French author Arthur Rimbaud (1854-1891). Britten immediately began setting selections by Rimbaud to music. The first two, Being Beauteous and Marine, were performed by the Swiss soprano, Sophie Wyss, in London in August 1939. Britten incorporated them into a full Rimbaud cycle, which he completed that October. He called it <em>Les Illuminations</em>, after the collection of poems and prose that Rimbaud had written during the 1870s.</p>
				<p>The premiere of the complete song cycle took place in London on 30 January 1940. Boyd Neel conducted his own string orchestra, with Wyss as the soloist. The music won high praise, such as these words from The New Statesman: &ldquo;This is a truly remarkable composition and justifies the expectations of great things from Britten. Each piece is a gem perfectly finished and original in character.&rdquo;</p>
				<p>Even at 26, Britten had developed an impressive skill at deploying the full colouristic resources of the string orchestra, as well as the infinite, mutually inspiring connections to be made between words and music. He mastered not only the single, stand-alone song, but the song cycle as well, of which Les Illuminations was to be but one of several outstanding examples. In it, he reflected, enriched and commented upon every facet of Rimbaud&rsquo;s vivid, often bizarre imagery, where the text is sometimes used more for the sounds it makes than to convey particular meanings.</p>
				<p>The Rimbaud / Britten <em>Les Illuminations</em> runs a striking emotional gamut, from the nightmarish urban bustle of Villes and Parade; to the melting beauty of Phrase; the erotic warmth of Antique, and Being Beauteous; the ironic humour of Royaut&eacute;; the exultant energy of Marine; and the aching tenderness of the closing song, D&eacute;part.</p>
				<p><strong>Oboe Concerto in A Minor, RV 463<br />Antonio Vivaldi</strong></p>
				<p>Vivaldi&rsquo;s busy and productive career as composer, violinist and teacher drew its due share of acclaim, but his reputation suffered a severe lapse following his death. His music&rsquo;s return to widespread currency dated only from the years following the Second World War. During that &lsquo;down time,&rsquo; virtually his only piece to remain in the standard repertoire was The Four Seasons. Its enduring popularity has been based to great degree on its nature as descriptive or programmatic music, an area in whose orchestral division Vivaldi made pioneering efforts.</p>
				<p>He played a major role in several other significant musical developments, the rise of the concerto above all. His 500-plus concertos (he composed far more pieces of this kind than any other composer, by a substantial margin) feature a wide variety of soloists. As you would expect, the lion&rsquo;s share, more than 200, focused on the instrument he played himself, the violin. He undoubtedly created some of these, and many of those for other instruments, for his pupils at the Pio Ospedale della Pietà, the largest of Venice&rsquo;s four schools that cared for orphaned, abandoned and indigent children. Other Vivaldi concertos were commissioned by wealthy individuals, or by concert societies in other cities.</p>
				<p>His numerous solo concertos for flute, oboe, and bassoon, and multiple-instrument concertos featuring the chalumeau, a forerunner of the clarinet, played a major role in increasing the reputation, and frequency of use, of the woodwind family. Previously they had played a subsidiary role to the strings.</p>
				<p>The Piet&agrave; had an oboe instructor during the early years that Vivaldi spent there, so there was a built-in need for music featuring it. Vivaldi composed nearly 20 concertos for oboe. This Concerto in A Minor is an adaptation of the Bassoon Concerto in the same key, RV 500. The fact that he didn&rsquo;t write out the solo part in full &mdash; only those passages which differ from the bassoon version &mdash; indicated that he wished to change as little as possible in the process of transcription.</p>
				<p>In the brisk outer movements, Vivaldi called upon the soloist to display nimbleness and agility on a virtuoso scale. The slow second movement makes quite different demands, requiring the oboist to sing an expressive, virtually operatic solo line.</p>
				<p><strong>Such Sweet Sorrow<br />John Estacio</strong></p>
				<p><em>The composer has written the following note:</em></p>
				<p>In many ways, I consider <em>Such Sweet Sorrow</em> to be a companion piece to another work I wrote for Winnipeg audiences, <em>Saudades</em> (1993). Both pieces were written while my life was in a state of flux, complete with a change of living location, a change in my personal life, a change of jobs, and a change in the people with whom I socially interacted. In retrospect, I can only assume that I have composed both works to serve as security blankets as I plowed through into a new life. This piece is a personal and melancholic requiem for the life I left behind.</p>
				<p>This commission gave me the opportunity to compose my own lyrical <em>Adagio for Strings</em>, a rare treat as I have scored most of my work for full orchestra. The piece follows two thematic ideas; the first is introduced in the very opening measures of the work, a simple melody that expands over the ensuing 29 measures. The lower strings play the second melody, while a solo violin elaborates rhapsodically. With the two themes introduced, the piece undergoes a development of these melodic ideas, at times with serenity and calm, at other times with impassioned restlessness.</p>
				<p>The middle of the piece features solos for the cello, viola and violin, solos that draw the piece to its climatic statement, a fiery juxtaposition of both the thematic ideas. Gradually, the intensity abates into a brief passage that has some of the players performing out of sync with each other. The piece eventually concludes with the solo violin and cello performing the opening theme in unison.</p>
				<p><strong>Sonata for Strings No. 3 in C Major<br />Gioachino Rossini</strong></p>
				<p>Rossini&rsquo;s career as the most popular operatic composer of the early nineteenth century lay ahead of him when he wrote this charming work. In 1804, when he was 12 (or three, if you choose to be strict about his being a leap-year baby), the family spent the summer in a village, Conventello, near Ravenna. Their host was Agostino Triossi, a wealthy businessman and amateur musician.</p>
				<p>That summer Rossini, who had barely begun any concentrated instruction in music, composed six delightful sonatas for strings. According to him, it took just three days to write them, forecasting the skill that later allowed him to compose full-length operas in a matter of weeks. The original scoring of the sonatas was for two violins, cello and double bass. This was unusual for the period in its substitution of the bass for the viola, but the bass was the instrument that Triossi played. It had recently become fashionable as a solo instrument, thanks to the prodigious virtuosity of soloists such as Domenico Dragonetti. Rossini gave it numerous solo passages throughout the sonatas.</p>
				<p>The first performances were given when the ink had barely dried. Late in life, Rossini wrote with typically wry humour about those occasions: &ldquo;The six horrendous sonatas were performed dreadfully by Triossi, contrabass, Morini (his cousin) first violin, the latter&rsquo;s brother, cello, and the second violin by myself, who was truth to tell the least dreadful of the lot.&rdquo; They have most often been performed, as No. 3 will be this evening, by a larger string ensemble.</p>
				<p>The existence of the original version was well documented, but the manuscript was missing and presumed lost. One hundred and fifty years after the music&rsquo;s creation, composer Alfredo Casella tracked it down to the Library of Congress in Washington, DC. The complete set was published in 1954. Transcriptions of some of them, for the standard string quartet scoring of two violins, viola and cello, had been published as far back as 1826, and an edition for flute, clarinet, bassoon and horn appeared in 1829. Both are regarded as the work of anonymous transcribers, not Rossini.</p>
				<p>Sonata No. 3 opens with a spirited and melodious Allegro. The following Andante is a rather serious affair, but Rossini makes no attempt to plumb depths of adult emotion. The finale is an enchanting set of variations on a catchy, comic-opera theme.</p>
			</div>
		</div><!-- /tab-content -->

		</div><!-- /tab content well -->

	</div><!-- /span6 tab area -->

	<div class="span2 offset1">
		<p class="fineprint">.</p>
	</div>

</div><!-- /row -->

<?php get_template_part('templates/content', 'concert'); ?>

</div><!-- /container -->
